FROM python:3.12-slim

WORKDIR /app

# Установка зависимостей
COPY telegram_bot/requirements.txt .
RUN pip install --no-cache-dir -r requirements.txt

# Копирование кода бота
COPY telegram_bot/ .

# Запуск бота
CMD ["python", "bot.py"]
